apiVersion : apps/v1
kind: Deployment
metadata:
  name: "nq-c018"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "nq-c018"
  template:
    metadata:
      labels:
        app: "nq-c018"
    spec:
      containers:
        - name: "nq-c018"
          image: "nanquanu.azurecr.io/nq"
          ports:
          - containerPort: 80