apiVersion: v1
kind: Service
metadata:
    name: "nq-c018"
    labels:
        app: "nq-c018"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "nq-c018"